services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app
    restart: always
    depends_on:
      - db
    working_dir: /var/www/
    volumes:
      - ../:/var/www

  nginx:
    image: nginx:1.27.5-alpine
    container_name: nginx
    restart: always
    depends_on:
      - db
    ports:
      - "8000:80"
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: app
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3308:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "9000:80"

volumes:
  mysql_data:
